/******************************************************************************
*  Generated by PSoC Designer 5.4.3191
******************************************************************************/
#include <m8c.h>
// LED_2Pin address and mask defines
#pragma	ioport	LED_2Pin_Data_ADDR:	0x0
BYTE			LED_2Pin_Data_ADDR;
#pragma	ioport	LED_2Pin_DriveMode_0_ADDR:	0x100
BYTE			LED_2Pin_DriveMode_0_ADDR;
#pragma	ioport	LED_2Pin_DriveMode_1_ADDR:	0x101
BYTE			LED_2Pin_DriveMode_1_ADDR;
#pragma	ioport	LED_2Pin_DriveMode_2_ADDR:	0x3
BYTE			LED_2Pin_DriveMode_2_ADDR;
#pragma	ioport	LED_2Pin_GlobalSelect_ADDR:	0x2
BYTE			LED_2Pin_GlobalSelect_ADDR;
#pragma	ioport	LED_2Pin_IntCtrl_0_ADDR:	0x102
BYTE			LED_2Pin_IntCtrl_0_ADDR;
#pragma	ioport	LED_2Pin_IntCtrl_1_ADDR:	0x103
BYTE			LED_2Pin_IntCtrl_1_ADDR;
#pragma	ioport	LED_2Pin_IntEn_ADDR:	0x1
BYTE			LED_2Pin_IntEn_ADDR;
#define LED_2Pin_MASK 0x2
// LED_2Pin Shadow defines
//   LED_2Pin_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define LED_2Pin_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
// LED_3Pin address and mask defines
#pragma	ioport	LED_3Pin_Data_ADDR:	0x0
BYTE			LED_3Pin_Data_ADDR;
#pragma	ioport	LED_3Pin_DriveMode_0_ADDR:	0x100
BYTE			LED_3Pin_DriveMode_0_ADDR;
#pragma	ioport	LED_3Pin_DriveMode_1_ADDR:	0x101
BYTE			LED_3Pin_DriveMode_1_ADDR;
#pragma	ioport	LED_3Pin_DriveMode_2_ADDR:	0x3
BYTE			LED_3Pin_DriveMode_2_ADDR;
#pragma	ioport	LED_3Pin_GlobalSelect_ADDR:	0x2
BYTE			LED_3Pin_GlobalSelect_ADDR;
#pragma	ioport	LED_3Pin_IntCtrl_0_ADDR:	0x102
BYTE			LED_3Pin_IntCtrl_0_ADDR;
#pragma	ioport	LED_3Pin_IntCtrl_1_ADDR:	0x103
BYTE			LED_3Pin_IntCtrl_1_ADDR;
#pragma	ioport	LED_3Pin_IntEn_ADDR:	0x1
BYTE			LED_3Pin_IntEn_ADDR;
#define LED_3Pin_MASK 0x4
// LED_3Pin Shadow defines
//   LED_3Pin_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define LED_3Pin_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
// LED_4Pin address and mask defines
#pragma	ioport	LED_4Pin_Data_ADDR:	0x0
BYTE			LED_4Pin_Data_ADDR;
#pragma	ioport	LED_4Pin_DriveMode_0_ADDR:	0x100
BYTE			LED_4Pin_DriveMode_0_ADDR;
#pragma	ioport	LED_4Pin_DriveMode_1_ADDR:	0x101
BYTE			LED_4Pin_DriveMode_1_ADDR;
#pragma	ioport	LED_4Pin_DriveMode_2_ADDR:	0x3
BYTE			LED_4Pin_DriveMode_2_ADDR;
#pragma	ioport	LED_4Pin_GlobalSelect_ADDR:	0x2
BYTE			LED_4Pin_GlobalSelect_ADDR;
#pragma	ioport	LED_4Pin_IntCtrl_0_ADDR:	0x102
BYTE			LED_4Pin_IntCtrl_0_ADDR;
#pragma	ioport	LED_4Pin_IntCtrl_1_ADDR:	0x103
BYTE			LED_4Pin_IntCtrl_1_ADDR;
#pragma	ioport	LED_4Pin_IntEn_ADDR:	0x1
BYTE			LED_4Pin_IntEn_ADDR;
#define LED_4Pin_MASK 0x8
// LED_4Pin Shadow defines
//   LED_4Pin_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define LED_4Pin_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
// LED_5Pin address and mask defines
#pragma	ioport	LED_5Pin_Data_ADDR:	0x0
BYTE			LED_5Pin_Data_ADDR;
#pragma	ioport	LED_5Pin_DriveMode_0_ADDR:	0x100
BYTE			LED_5Pin_DriveMode_0_ADDR;
#pragma	ioport	LED_5Pin_DriveMode_1_ADDR:	0x101
BYTE			LED_5Pin_DriveMode_1_ADDR;
#pragma	ioport	LED_5Pin_DriveMode_2_ADDR:	0x3
BYTE			LED_5Pin_DriveMode_2_ADDR;
#pragma	ioport	LED_5Pin_GlobalSelect_ADDR:	0x2
BYTE			LED_5Pin_GlobalSelect_ADDR;
#pragma	ioport	LED_5Pin_IntCtrl_0_ADDR:	0x102
BYTE			LED_5Pin_IntCtrl_0_ADDR;
#pragma	ioport	LED_5Pin_IntCtrl_1_ADDR:	0x103
BYTE			LED_5Pin_IntCtrl_1_ADDR;
#pragma	ioport	LED_5Pin_IntEn_ADDR:	0x1
BYTE			LED_5Pin_IntEn_ADDR;
#define LED_5Pin_MASK 0x10
// LED_5Pin Shadow defines
//   LED_5Pin_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define LED_5Pin_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
// LED_6Pin address and mask defines
#pragma	ioport	LED_6Pin_Data_ADDR:	0x0
BYTE			LED_6Pin_Data_ADDR;
#pragma	ioport	LED_6Pin_DriveMode_0_ADDR:	0x100
BYTE			LED_6Pin_DriveMode_0_ADDR;
#pragma	ioport	LED_6Pin_DriveMode_1_ADDR:	0x101
BYTE			LED_6Pin_DriveMode_1_ADDR;
#pragma	ioport	LED_6Pin_DriveMode_2_ADDR:	0x3
BYTE			LED_6Pin_DriveMode_2_ADDR;
#pragma	ioport	LED_6Pin_GlobalSelect_ADDR:	0x2
BYTE			LED_6Pin_GlobalSelect_ADDR;
#pragma	ioport	LED_6Pin_IntCtrl_0_ADDR:	0x102
BYTE			LED_6Pin_IntCtrl_0_ADDR;
#pragma	ioport	LED_6Pin_IntCtrl_1_ADDR:	0x103
BYTE			LED_6Pin_IntCtrl_1_ADDR;
#pragma	ioport	LED_6Pin_IntEn_ADDR:	0x1
BYTE			LED_6Pin_IntEn_ADDR;
#define LED_6Pin_MASK 0x20
// LED_6Pin Shadow defines
//   LED_6Pin_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define LED_6Pin_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
// LED_7Pin address and mask defines
#pragma	ioport	LED_7Pin_Data_ADDR:	0x0
BYTE			LED_7Pin_Data_ADDR;
#pragma	ioport	LED_7Pin_DriveMode_0_ADDR:	0x100
BYTE			LED_7Pin_DriveMode_0_ADDR;
#pragma	ioport	LED_7Pin_DriveMode_1_ADDR:	0x101
BYTE			LED_7Pin_DriveMode_1_ADDR;
#pragma	ioport	LED_7Pin_DriveMode_2_ADDR:	0x3
BYTE			LED_7Pin_DriveMode_2_ADDR;
#pragma	ioport	LED_7Pin_GlobalSelect_ADDR:	0x2
BYTE			LED_7Pin_GlobalSelect_ADDR;
#pragma	ioport	LED_7Pin_IntCtrl_0_ADDR:	0x102
BYTE			LED_7Pin_IntCtrl_0_ADDR;
#pragma	ioport	LED_7Pin_IntCtrl_1_ADDR:	0x103
BYTE			LED_7Pin_IntCtrl_1_ADDR;
#pragma	ioport	LED_7Pin_IntEn_ADDR:	0x1
BYTE			LED_7Pin_IntEn_ADDR;
#define LED_7Pin_MASK 0x40
// LED_7Pin Shadow defines
//   LED_7Pin_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define LED_7Pin_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
// LED_8Pin address and mask defines
#pragma	ioport	LED_8Pin_Data_ADDR:	0x0
BYTE			LED_8Pin_Data_ADDR;
#pragma	ioport	LED_8Pin_DriveMode_0_ADDR:	0x100
BYTE			LED_8Pin_DriveMode_0_ADDR;
#pragma	ioport	LED_8Pin_DriveMode_1_ADDR:	0x101
BYTE			LED_8Pin_DriveMode_1_ADDR;
#pragma	ioport	LED_8Pin_DriveMode_2_ADDR:	0x3
BYTE			LED_8Pin_DriveMode_2_ADDR;
#pragma	ioport	LED_8Pin_GlobalSelect_ADDR:	0x2
BYTE			LED_8Pin_GlobalSelect_ADDR;
#pragma	ioport	LED_8Pin_IntCtrl_0_ADDR:	0x102
BYTE			LED_8Pin_IntCtrl_0_ADDR;
#pragma	ioport	LED_8Pin_IntCtrl_1_ADDR:	0x103
BYTE			LED_8Pin_IntCtrl_1_ADDR;
#pragma	ioport	LED_8Pin_IntEn_ADDR:	0x1
BYTE			LED_8Pin_IntEn_ADDR;
#define LED_8Pin_MASK 0x80
// LED_8Pin Shadow defines
//   LED_8Pin_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define LED_8Pin_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
